import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { MuiThemeProvider } from "@/app/providers/ThemeProvider";
import "../styles/globals.scss";

const dmSans = DM_Sans({
  variable: "--font-family",
  weight: ["400", "500", "700"],
  subsets: ["latin", "latin-ext"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Home | Box Cars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body>
        <MuiThemeProvider>{children}</MuiThemeProvider>
      </body>
    </html>
  );
}
